### ISSUE TITLE
Composer Installation Error

### ISSUE THREAD

**Issue by geraldokandonga** [agungsugiarto/codeigniter4-authentication-jwt#2]
Thank you very much for your good work

However when I try installing the library I get the following composer error:

`[InvalidArgumentException]                                                                                                                                                                                        
  Could not find a version of package agungsugiarto/codeigniter4-authentication-jwt matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.`

How best can I use this library? 

Thank you

**Comment by agungsugiarto** [comment]
Hello @geraldokandonga, since this package is early on development you need few change on your file `composer.json`.

Reference
- https://getcomposer.org/doc/04-schema.md#minimum-stability
- https://github.com/agungsugiarto/codeigniter4-authentication-demo/blob/79a0d1a758d02195a5e1c8341b56d1bf1912a1ef/composer.json#L36-L37

**Comment by geraldokandonga** [comment]
Lovely that worked like a charm,

Second question is: How do i define the Auth Config to be used for this library?

Thank you in advance
